"""Agent-Skill rendering for the workspace.

Pi and Codex auto-discover Agent Skills under .agents/skills/ (project trust).
Each instance command (commands/<name>.md) is rendered into a skill with
sanitized name and frontmatter. This is a pure port of the old launcher's
skill rendering.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

from .util import warn

MANAGED_MARKER = "Generated by agentic-workspace"


def sanitize_skill_name(name: str) -> str:
    """Lowercase and keep only [a-z0-9-] for a valid pi Agent Skill name."""
    s = name.lower()
    s = re.sub(r"[^a-z0-9-]", "-", s)
    s = re.sub(r"-{2,}", "-", s)
    return s.strip("-")


def strip_frontmatter(text: str) -> str:
    """Drop a leading YAML frontmatter block (--- ... ---)."""
    if text.startswith("---\n"):
        parts = text.split("---\n", 2)
        if len(parts) == 3:
            return parts[2]
    return text


def extract_description(text: str) -> str:
    m = re.search(r"^description:\s*\"?([^\"]*?)\"?\s*$", text, re.MULTILINE)
    return m.group(1).strip() if m else ""


def render_skill(name: str, description: str, source: str, target: Path) -> None:
    body = strip_frontmatter(source).replace(
        "$ARGUMENTS", "any extra user text that accompanied the skill invocation"
    )
    content = (
        f"---\nname: {name!r}\ndescription: {description!r}\n---\n\n"
        f"<!-- Generated by agentic-workspace. Edit commands/{name}.md to change this skill. -->\n\n"
        f"This project skill mirrors the `{name}` research command.\n\n"
        "If the user supplied extra text alongside this skill invocation, treat "
        "that text as the command argument.\n\n"
        f"{body}"
    )
    target.write_text(content)


def install_project_skills(workspace: Path, agent_root: Path, commands: list[str]) -> None:
    """Render the instance's commands as Agent Skills in the workspace."""
    skills_dir = workspace / ".agents" / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    for cmd in commands:
        src = agent_root / "commands" / f"{cmd}.md"
        if not src.is_file():
            continue
        skill_name = sanitize_skill_name(cmd)
        source_text = src.read_text(encoding="utf-8")
        description = extract_description(source_text) or skill_name

        skill_dir = skills_dir / skill_name
        target = skill_dir / "SKILL.md"
        if target.is_file() and MANAGED_MARKER not in target.read_text(encoding="utf-8"):
            warn(f"Skipping existing skill at {target} (not managed by agentic-workspace)")
            continue

        skill_dir.mkdir(parents=True, exist_ok=True)
        render_skill(skill_name, description, source_text, target)

        # Copy supporting skill assets (commands/<cmd>/...) next to SKILL.md,
        # so skills can ship helper scripts (e.g. stylelint.py).
        assets = src.parent / skill_name
        if assets.is_dir():
            shutil.copytree(assets, skill_dir, dirs_exist_ok=True)

        # Remove a previously generated skill dir under the unsanitized name,
        # so pi never sees both (it rejects names with invalid characters).
        if skill_name != cmd and (skills_dir / cmd).is_dir():
            shutil.rmtree(skills_dir / cmd)
